ViewModels/BuyAddArticleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using TrendyShop.Models;

namespace TrendyShop.ViewModels
{
    public class BuyAddArticleViewModel
    {
        //public int Id { get; set; }

        public Add Add { get; set; }

        public string CustomerId { get; set; }
        
        //[ForeignKey("CustomerId")]
        //public User Customer { get; set; }


        [Range(1, int.MaxValue, ErrorMessage ="Especifique una cantidad válida para su compra")]
        [Display(Name = "Cantidad a ordenar")]
        //[Required(ErrorMessage ="Por favor especifique el número de artículos que desea adquirir")]
        public int AmountToBuy { get; set; }

        [Display(Name = "¿Utilizar dirección asociada a tarjeta?")]
        public bool ShippingToCardAddress { get; set; }

        [Display(Name = "Dirección de envio")]
        [Required(ErrorMessage ="Especifique una dirección para el envío")]
        public string Address { get; set; }

        //En menos de una semana, en el proximo mes, blabla 
        [Display(Name = "Rapidez del envio requerida")]
        public int ShippingMode { get; set; }

        public float ShippingCharge { get; set; }

        ////[MinLength(11), MaxLength(11)]
        //[Range(1,99999999999,ErrorMessage ="Por favor inserte un número de trajeta válido")]
        //[Display(Name = "Número de tarjeta de crédito")]
        //[Required(ErrorMessage ="Es necesario que inserte una  tarjeta para efectuar la compra")]
        //public int Card { get; set; }
    }
}

ViewModels/BuyAuctionArticleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using TrendyShop.Models;

namespace TrendyShop.ViewModels
{
    public class BuyAuctionArticleViewModel
    {
        public Auction Auction { get; set; }

        public string CustomerId { get; set; }
        
        [Display(Name = "¿Utilizar dirección asociada a tarjeta?")]
        public bool ShippingToCardAddress { get; set; }

        [Display(Name = "Dirección de envio")]
        public string Address { get; set; }

        [Display(Name = "Rapidez del envio requerida")]
        [Required(ErrorMessage = "Especifique una dirección para el envío")]
        public int ShippingMode { get; set; }

        public float ShippingCharge { get; set; }
    }
}

ViewModels/BuySCArticleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TrendyShop.ViewModels
{
    public class BuySCArticleViewModel
    {
        public IList<ShoppingListArticuleViewModel> SCArticles{ get; set; }

        public string CustomerId { get; set; }

        //[Display(Name = "¿Utilizar dirección asociada a tarjeta?")]
        //public bool ShippingToCardAddress { get; set; }

        [Display(Name = "Dirección de envio")]
        public string Address { get; set; }

        //[Display(Name = "Rapidez del envio requerida")]
        //[Required(ErrorMessage = "Especifique una dirección para el envío")]
        //public int ShippingMode { get; set; }

        public float ShippingCharge { get; set; }

        public bool Incomplete { get;  set; }
        public double Total { get; set; }
    }
}

Controllers/BuyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TrendyShop.Data;
using Microsoft.EntityFrameworkCore;
using TrendyShop.ViewModels;
using TrendyShop.Models;

namespace TrendyShop.Controllers
{
    public class BuyController : Controller
    {
        private EFDbContext context;

        public BuyController(EFDbContext ctx)
        {
            context = ctx;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult BuyAddArticle(string uid, int aid)
        {
            var userName = User.Identity.Name;

            if (userName == null)
            {
                return RedirectToAction("Login", "User");
            }
            var userId = context.Users.Single(u => u.UserName == userName).Id;

            var add = context.Adds.Include(a => a.Article)
                .Include(a => a.User)
                .Single(a => a.UserId == uid && a.ArticleId == aid);

            var buyViewModel = new BuyAddArticleViewModel
            {
                Add = add,
                CustomerId = userId
            };

            return View(buyViewModel);
        }

        [HttpPost]
        public IActionResult EffectBuy(BuyAddArticleViewModel bvm)
        {
            var add = context.Adds.Include(a => a.Article)
                .Single(a => a.ArticleId == bvm.Add.ArticleId && a.UserId == bvm.Add.UserId);

            if (bvm.AmountToBuy > bvm.Add.Amount)
            {
                ModelState.AddModelError("AmountToBuy", "La cantidad a comprar debe ser menor que la disponible en el anuncio.");
            }
            if (!ModelState.IsValid)
            {
                BuyAddArticleViewModel newBvw = new BuyAddArticleViewModel
                {
                    Add = add,
                    CustomerId = bvm.CustomerId,
                    AmountToBuy = bvm.AmountToBuy,
                    Address = bvm.Address
                };
                return View("BuyAddArticle", newBvw);
            }

            var newOrder = new Order
            {
                CustomerId = bvm.CustomerId,
                ArticleId = bvm.Add.ArticleId,
                Date = DateTime.Now,
                Amount = bvm.AmountToBuy,
                Address = bvm.Address,
                ShippingCharge = bvm.ShippingCharge
            };

            context.Orders.Add(newOrder);
            context.SaveChanges();

            var totalCharge = newOrder.Amount * bvm.Add.Article.Price + newOrder.ShippingCharge;

            return RedirectToAction("GetPaymentMethod", "PaymentGateway",
                new { userId = newOrder.CustomerId, articleId = newOrder.ArticleId,
                    orderDateTicks = newOrder.Date.Ticks, charge = totalCharge });
        }

        public IActionResult BuySCArticles()
        {
            var userName = User.Identity.Name;
            var userId = context.Users.Single(u => u.UserName == userName).Id;

            var carItems = (from a in context.ShoppingCars
                            join b in context.ShoppingLists on a.ShoppingListId equals b.ShoppingListId
                            join c in context.ShoppingList_Articles on b.ShoppingListId equals c.ShoppingListId
                            where b.IsMainList == true && a.UserId == userId
                            select new { c.Article, c.Amount }).ToList();

            if (carItems.Count == 0)
                return RedirectToAction("Index", "ShoppingCart");

            var buyViewModel = new BuySCArticleViewModel
            {
                CustomerId = userId,
                Total = 0
            };

            List<ShoppingListArticuleViewModel> articlesToBuy = new List<ShoppingListArticuleViewModel>();

            foreach (var item in carItems)
            {
                var ad = context.Adds.Include(a => a.User).SingleOrDefault(b => b.ArticleId == item.Article.ArticleId);

                ShoppingListArticuleViewModel slArticle = new ShoppingListArticuleViewModel
                {
                    ArticleId = item.Article.ArticleId,
                    Name = item.Article.Name,
                    Price = item.Article.Price
                };

                if (ad.Amount >= item.Amount)//si hay disponible la ctdad necesaria compralo todo
                {
                    slArticle.Amount = item.Amount;
                    articlesToBuy.Add(slArticle);
                    buyViewModel.Total += slArticle.TotalPrice;
                }
                else//sino comprar todo lo que queda y reportar que no se pudo obtener todo, a no ser que se haya agotado.
                {
                    if (ad.Amount > 0)
                    {
                        slArticle.Amount = ad.Amount;
                        articlesToBuy.Add(slArticle);
                    }
                    buyViewModel.Incomplete = true;
                    buyViewModel.Total += slArticle.TotalPrice;
                }
            }

            buyViewModel.SCArticles = articlesToBuy;

            return View(buyViewModel);
        }

        [HttpPost]
        public IActionResult EffectSCBuy(BuySCArticleViewModel bvm)
        {
            if (!ModelState.IsValid)
            {
                BuySCArticleViewModel newBvm = new BuySCArticleViewModel
                {
                    CustomerId = bvm.CustomerId,
                    Total = bvm.Total,
                    Incomplete = bvm.Incomplete,
                    Address = bvm.Address,
                    SCArticles = bvm.SCArticles
                };
                return View("BuySCArticles", newBvm);
            }
            var date = DateTime.Now;
            foreach (var article in bvm.SCArticles)
            {
                var newOrder = new Order
                {//poner un booleano o algo que represente que la entrega fue de shopping car, por tanto el cobro por esta es en general
                    CustomerId = bvm.CustomerId,
                    ArticleId = article.ArticleId,
                    Date = date,
                    Amount = article.Amount,
                    Address = bvm.Address,
                    ShippingCharge = bvm.ShippingCharge,
                    SharedOrder = true
                };

                context.Orders.Add(newOrder);
                context.SaveChanges();
            }


            var totalCharge = bvm.Total + bvm.ShippingCharge;

            return RedirectToAction("GetPaymentMethod", "PaymentGateway", new { userId = bvm.CustomerId, articleId = -1, orderDateTicks = date.Ticks, charge = totalCharge, orderType = 1 });
        }

        public IActionResult BuyAuctionArticle(int aid)
        {
            var userName = User.Identity.Name;

            if (userName == null)
            {
                return RedirectToAction("Login", "User");
            }
            var userId = context.Users.Single(u => u.UserName == userName).Id;

            var auction = context.Auctions.Include(a => a.Article).Include(a => a.LastBid)
                .Include(a => a.User)
                .Single(a => a.ArticleId == aid);
            
            if (auction.User.UserName == userName)
            {
                return RedirectToAction("Index", "Auction"); //Si nadie pujó en la subasta
            }

            var buyViewModel = new BuyAuctionArticleViewModel
            {
                Auction = auction,
                CustomerId = userId
            };

            return View(buyViewModel);
        }

        [HttpPost]
        public IActionResult EffectAuctionBuy(BuyAuctionArticleViewModel bvm)
        {
            var auction = context.Auctions.Include(a => a.Article).Include(a => a.LastBid)
                .Include(a => a.User)
                .Single(a => a.UserId == bvm.Auction.UserId && a.ArticleId == bvm.Auction.ArticleId);

            if (!ModelState.IsValid)
            {
                BuyAuctionArticleViewModel newBvw = new BuyAuctionArticleViewModel
                {
                    Auction = auction,
                    CustomerId = bvm.CustomerId,
                    Address = bvm.Address
                };
                return View("BuyAuctionArticle", newBvw);
            }

            var newOrder = new AuctionOrder
            {
                CustomerId = bvm.CustomerId,
                ArticleId = bvm.Auction.ArticleId,
                Date = DateTime.Now,
                Address = bvm.Address,
                ShippingCharge = bvm.ShippingCharge
            };

            context.AuctionOrders.Add(newOrder);
            context.SaveChanges();

            var totalCharge = auction.CurrentPrice + newOrder.ShippingCharge;

            return RedirectToAction("GetPaymentMethod", "PaymentGateway",
                new
                {
                    userId = newOrder.CustomerId,
                    articleId = newOrder.ArticleId,
                    orderDateTicks = newOrder.Date.Ticks,
                    charge = totalCharge,
                    orderType = 2
                });
        }

        public IActionResult CloseOrder(string userId, int articleId, long dateTicks, int orderType)
        {
            if (orderType == 1)
            {
                return CloseShoppingCartOrders(userId, dateTicks);
            }
            else if (orderType == 2)
            {
                return CloseAuctionOrder(userId, articleId, dateTicks);
            }
            else
            {
                return CloseRegularOrder(userId, articleId, dateTicks);
            }
        }

        private void closeRegularOrder(string userId, int articleId, long dateTicks) 
        {
            var date = new DateTime(dateTicks);
            var order = context.Orders.Single(o => o.CustomerId == userId && o.ArticleId == articleId && o.Date == date);
            order.Paid = true;
            context.SaveChanges();

Views/Buy/BuyAddArticle.cshtml
@model TrendyShop.ViewModels.BuyAddArticleViewModel


<div class="col-lg-5 mx-auto mt-4">
    <div class="card">
        <div class="card-body">
            <h1 class="card-title border-bottom">Compra de @Model.Add.Article.Name</h1>
            @using (Html.BeginForm("EffectBuy", "Buy", FormMethod.Post, new { id = "bform" }))
            {
                <div class=" form-group">
                    @Html.LabelFor(m => m.AmountToBuy)
                    @Html.TextBoxFor(m => m.AmountToBuy, new { @class = "form-control", @id = "amount" })
                    @Html.ValidationMessageFor(m => m.AmountToBuy)
                </div>

                <div class=" form-group">
                    @Html.LabelFor(m => m.Address)
                    @Html.TextBoxFor(m => m.Address, new { @class = "form-control", @id = "address" })
                    @Html.ValidationMessageFor(m => m.Address)
                </div>

                <div class="d-flex">
                    <button class="btn btn-secondary ml-auto" type="button" data-toggle="modal" data-target="#confirmodal">Realizar pedido</button>
                    <button class="btn btn-dark ml-1" type="button" onclick="location.pathname='/Add'">Cancelar</button>
                </div>

                @Html.HiddenFor(m => m.Add.UserId)
                @Html.HiddenFor(m => m.Add.ArticleId)
                @Html.HiddenFor(m => m.Add.Article.Name)
                @Html.HiddenFor(m => m.Add.Article.Price)
                @Html.HiddenFor(m => m.Add.Amount)
                @Html.HiddenFor(m => m.CustomerId)
            }
        </div>
    </div>
</div>

<div class="modal fade" id="confirmodal" tabindex="-1" role="dialog" aria-labelledby="ConfirmationModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="ConfirmationModalLongTitle">¿Está seguro que desea realizar esta compra?</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Se aplicará un extra por el envio.</h5>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary ml-auto" onclick="finishOperation()">Continuar</button>
                <button class="btn btn-dark ml-1" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

<script>
    var shippingCharge = 0;

    document.getElementById("amount").select();

    function validateForm() {
        var amount = parseInt(document.getElementById('amount').value);
        var amountAvailable = @Model.Add.Amount;
        var address = document.getElementById('address').value;
              
        if (amount == "" || isNaN(amount) || amount > amountAvailable) {
            alert("Por favor especifique una cantidad positiva y menor que la restante para su compra");
            return false;
        }

        if (address == "" || address == null){
            alert("Por favor especifique una dirección a la cual enviar el pedido");
            return false;
        }

        return true;
    }
    
    function finishOperation() {
        //isvalid = validateForm();
        //if (isvalid) {
        saveShippingCharge();
        submitForm();
        //}
    }

    function submitForm() {
        document.getElementById('bform').submit();
    }

    function saveShippingCharge() {
        shippingCharge = Math.floor((Math.random() * 10) + 1);

        form = document.getElementById('bform');

        var input = document.createElement("INPUT");
        input.setAttribute("type", "hidden");
        input.setAttribute("value", shippingCharge);
        input.setAttribute("name", "ShippingCharge");
        form.appendChild(input);
    }
</script>

Views/Buy/BuyAuctionArticle.cshtml
@model TrendyShop.ViewModels.BuyAuctionArticleViewModel

@*@{
    ViewData["Title"] = "BuyAuctionArticle";
}*@

<div class="col-lg-5 mx-auto mt-4">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title border-bottom">Felicidades por su reciente apuesta ganadora.</h5>
            <h5 class="card-title border-bottom">Llegó la hora de adquirir su @Model.Auction.Article.Name</h5>
            @using (Html.BeginForm("EffectAuctionBuy", "Buy", FormMethod.Post, new { id = "bform" }))
            {
                <div class=" form-group">
                    @Html.LabelFor(m => m.Address)
                    @Html.TextBoxFor(m => m.Address, new { @class = "form-control", @id = "address" })
                    @Html.ValidationMessageFor(m => m.Address)
                </div>

                <div class="d-flex">
                    <button class="btn btn-secondary ml-auto" type="button" data-toggle="modal" data-target="#confirmodal">Realizar pedido</button>
                    <button class="btn btn-dark ml-1" type="button" onclick="location.pathname='/Add'">Cancelar</button>
                </div>

                @Html.HiddenFor(m => m.Auction.UserId)
                @Html.HiddenFor(m => m.Auction.ArticleId)
                @Html.HiddenFor(m => m.Auction.Article.Name)
                @Html.HiddenFor(m => m.Auction.Article.Price)
                @Html.HiddenFor(m => m.CustomerId)
            }
        </div>
    </div>
</div>

<div class="modal fade" id="confirmodal" tabindex="-1" role="dialog" aria-labelledby="ConfirmationModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="ConfirmationModalLongTitle">¿Está seguro que desea realizar esta compra?</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Se aplicará un extra por el envio.</h5>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary ml-auto" onclick="finishOperation()">Continuar</button>
                <button class="btn btn-dark ml-1" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

<script>
    var shippingCharge = 0;

    document.getElementById("amount").select();
    
    function validateForm() {
        var address = document.getElementById('address').value;

        if (address == "" || address == null){
            alert("Por favor especifique una dirección a la cual enviar su más reciente adquisición.");
            return false;
        }

        return true;
    }

    function finishOperation() {
        isvalid = validateForm();
        if (isvalid) {
            saveShippingCharge();
            submitForm();
        }
    }

    function submitForm() {
        document.getElementById('bform').submit();
    }

    function saveShippingCharge() {
        shippingCharge = Math.floor((Math.random() * 10) + 1);

        form = document.getElementById('bform');

        var input = document.createElement("INPUT");
        input.setAttribute("type", "hidden");
        input.setAttribute("value", shippingCharge);
        input.setAttribute("name", "ShippingCharge");
        form.appendChild(input);
    }
</script>

Views/Buy/BuySCArticles.cshtml
@model TrendyShop.ViewModels.BuySCArticleViewModel
@*@{
        ViewData["Title"] = "BuySCArticles";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }*@

<div class="col-lg-5 mx-auto mt-4">
    <div class="card">
        <div class="card-body">
            <h3 class="card-title border-bottom">Compra de artículos del carrito</h3>
            @using (Html.BeginForm("EffectSCBuy", "Buy", FormMethod.Post, new { id = "bform" }))
            {
                <div class=" form-group">
                    @Html.LabelFor(m => m.Address)
                    @Html.TextBoxFor(m => m.Address, new { @class = "form-control", @id = "address" })
                    @Html.ValidationMessageFor(m => m.Address)
                </div>

                <div class="d-flex">
                    <button class="btn btn-secondary ml-auto" type="button" data-toggle="modal" data-target="#confirmodal">Realizar pedido</button>
                    <button class="btn btn-dark ml-1" type="button" onclick="location.pathname='/Add'">Cancelar</button>
                </div>

                @for (int i = 0; i < Model.SCArticles.Count(); i++)
                {
                    @Html.HiddenFor(m => m.SCArticles[i].ArticleId)
                    @Html.HiddenFor(m => m.SCArticles[i].Name)
                    @Html.HiddenFor(m => m.SCArticles[i].Amount)
                    @Html.HiddenFor(m => m.SCArticles[i].Price)
                    @Html.HiddenFor(m => m.SCArticles[i].TotalPrice)

                }
                @Html.HiddenFor(m => m.CustomerId)
                @Html.HiddenFor(m => m.Total)
                @Html.HiddenFor(m => m.Incomplete)
            }
        </div>
    </div>
</div>

<div class="modal fade" id="confirmodal" tabindex="-1" role="dialog" aria-labelledby="ConfirmationModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="ConfirmationModalLongTitle">¿Está seguro que desea realizar esta compra?</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @if (Model.Incomplete)
                {
                    <h5>Lo sentimos pero algunos de los productos solicitados se han agotado, la lista de compra a efectuar se redujo a:</h5>
                }
                <table class="table table-bordered">
                    <tr>
                        <th>Producto</th>
                        <th>Precio</th>
                        <th>Cantidad</th>
                        <th>Total</th>
                    </tr>
                    @foreach (var article in Model.SCArticles)
                    {
                        <tr>
                            <td>@article.Name</td>
                            <td>@article.Price</td>
                            <td>@article.Amount</td>
                            <td>@article.TotalPrice</td>
                        </tr>
                    }
                    <tr>
                        <td> </td>
                        <td> </td>
                        <td> </td>
                        <td>@Model.Total </td>
                    </tr>
                </table>
                <h5>Se aplicará un extra por el envio.</h5>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary ml-auto" onclick="finishOperation()">Continuar</button>
                <button class="btn btn-dark ml-1" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

<script>
    var shippingCharge = 0;

    function validateForm() {
        var address = document.getElementById('address').value;

        if (address == "" || address == null) {
            alert("Por favor especifique una dirección a la cual enviar su más reciente adquisición.");
            return false;
        }

        return true;
    }

    function finishOperation() {
        isvalid = validateForm();
        if (isvalid) {
            saveShippingCharge();
            submitForm();
        }
    }

    function submitForm() {
        document.getElementById('bform').submit();
    }

    function saveShippingCharge() {
        shippingCharge = Math.floor((Math.random() * 10) + 1);

        form = document.getElementById('bform');

        var input = document.createElement("INPUT");
        input.setAttribute("type", "hidden");
        input.setAttribute("value", shippingCharge);
        input.setAttribute("name", "ShippingCharge");
        form.appendChild(input);
    }
</script>