Controllers/PaymentGatewayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TrendyShop.Data;
using TrendyShop.Models;
using TrendyShop.ViewModels;

namespace TrendyShop.Controllers
{
    public class PaymentGatewayController : Controller
    {
        private EFDbContext context;

        public PaymentGatewayController(EFDbContext ctx)
        {
            context = ctx;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetPaymentMethod(string userId, int articleId, long orderDateTicks, double charge, int orderType = 3)
        {
            var cards = context.User_Cards.Where(c => c.UserId == userId).ToList();

            PaymentMethodViewModel pmvm = new PaymentMethodViewModel
            {
                UserId = userId,
                ArticleId = articleId,
                DateTicks = orderDateTicks,
                Charge = charge,
                Cards = cards,
                OrderType = orderType
            };
            return View(pmvm);
        }

        [HttpPost]
        public IActionResult FinishPayment(PaymentMethodViewModel pmvm)
        {
            if (!ModelState.IsValid)
            {
                var cards = context.User_Cards.Where(c => c.UserId == pmvm.UserId).ToList();
                PaymentMethodViewModel newpmvm = new PaymentMethodViewModel
                {
                    UserId = pmvm.UserId,
                    SellerId = pmvm.SellerId,
                    ArticleId = pmvm.ArticleId,
                    DateTicks = pmvm.DateTicks,
                    Charge = pmvm.Charge,
                    Cards = cards,
                    CardNumber = pmvm.CardNumber,
                    NameOnCard = pmvm.NameOnCard,
                    OrderType = pmvm.OrderType
                };
                return RedirectToAction("GetPaymentMethod", newpmvm);
            }

            var nameOnCard = pmvm.NameOnCard;
            var cardNumber = pmvm.CardNumber;
            if (pmvm.NameOnCard == null || pmvm.CardNumber == null)
            {
                nameOnCard = context.User_Cards.Single(uc => uc.UserId == pmvm.UserId 
                && uc.CardNumber == pmvm.SelectedCardNumber).NameOnCard;
                cardNumber = pmvm.SelectedCardNumber;
            }
            else
            {
                var user_card = new User_Card
                {
                    UserId = pmvm.UserId,
                    CardNumber = cardNumber,
                    NameOnCard = nameOnCard
                };
                var cardInDb = context.User_Cards
                    .SingleOrDefault(uc => uc.UserId == user_card.UserId && uc.CardNumber == user_card.CardNumber);
                if (cardInDb == null)
                {
                    context.User_Cards.Add(user_card);
                    context.SaveChanges();
                }
            }
          
            //aqui es donde se deberia hacer las transacciones entre las cuentas del comprador y el o los vendedores
            return RedirectToAction("CloseOrder", "Buy", 
                new { userId = pmvm.UserId, articleId = pmvm.ArticleId, dateTicks = pmvm.DateTicks,
                    orderType = pmvm.OrderType});
        }
    }
}

Views/PaymentGateway/GetPaymentMethod.cshtml
@model TrendyShop.ViewModels.PaymentMethodViewModel

<div class="col-lg-5 mx-auto mt-4">
    <div class="card">
        <div class="card-body">
            <h1 class="card-title border-bottom">Complete su orden: </h1>
            @using (Html.BeginForm("FinishPayment", "PaymentGateway", FormMethod.Post, new { id = "pform" }))
            {
                <div class=" form-group">
                    @Html.LabelFor(m => m.NameOnCard)
                    @Html.TextBoxFor(m => m.NameOnCard, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.NameOnCard)
                </div>

                <div class=" form-group">
                    @Html.LabelFor(m => m.CardNumber)
                    @Html.TextBoxFor(m => m.CardNumber, new { @class = "form-control"})
                    @Html.ValidationMessageFor(m => m.CardNumber)
                </div>

                <h3>O escoja una de las registradas:</h3>

                <div class=" form-group">
                    @Html.LabelFor(m => m.SelectedCardNumber)
                    @Html.DropDownListFor(m => m.SelectedCardNumber, new SelectList(Model.Cards, "CardNumber", "CardNumber"), "", new { @class = "form-control" })
                </div>

                @Html.HiddenFor(m => m.UserId)
                @Html.HiddenFor(m => m.ArticleId)
                @Html.HiddenFor(m => m.DateTicks)
                @Html.HiddenFor(m => m.Charge)
                @Html.HiddenFor(m => m.OrderType)
            }


            <div class="d-flex">
                <button class="btn btn-secondary ml-auto" type="button" data-toggle="modal" data-target="#confirmodal">Realizar pago</button>
                <form asp-action="CancelOrder" asp-controller="Buy" asp-route-userId=@Model.UserId asp-route-articleId=@Model.ArticleId asp-route-dateTicks=@Model.DateTicks asp-route-orderType=@Model.OrderType>
                    <button class="btn btn-dark ml-1" type="submit">Cancelar</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="confirmodal" tabindex="-1" role="dialog" aria-labelledby="ConfirmationModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ConfirmationModalLongTitle">Confirmación de pago</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h6>Se descontará @Model.Charge de su cuenta. ¿Desea continuar?</h6>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary ml-auto" onclick="finishOperation()">Continuar</button>
                <button class="btn btn-dark ml-1" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

<script>
    var usedCards = []
    function insertData() {
        var isValid = validateForm();

        if (isValid) {
            $('#confirmodal').modal()
        }
    }

    function validateForm() {
        nameOnCard = document.getElementById("NameOnCard").value;
        cardNumber = document.getElementById("CardNumber").value;
        var dropDownList = document.getElementById("SelectedCardNumber");
        cardNumberDDL = dropDownList.options[dropDownList.selectedIndex].text;

        //cards most have from 13 - 18 digits
        if (cardNumberDDL != "" && (nameOnCard != "" || cardNumber != "")) {
            alert("Sólo puede elegir una tarjeta para realizar el pago.")
            return false;
        }
        if (cardNumberDDL == "" && nameOnCard == "" && cardNumber == "") {
            alert("Debe elegir una tarjeta para realizar el pago.")
            return false;
        }
        if (cardNumberDDL == "") {
            if (nameOnCard == "") {
                alert("Por favor especifique un nombre de tarjeta válido.");
                return false;
            }
            if (isNaN(cardNumber) || cardNumber.length < 13 || cardNumber.length > 18) {
                alert("Por favor especifique un número de tarjeta válido. Debe contener entre 13 y 18 dígitos.");
                return false;
            }
        }
        return true;
    }

    function finishOperation() {
        isValid = validateForm();

        if (isValid) {
            newCardNumber = document.getElementById("CardNumber").value;
            var dropDownList = document.getElementById("SelectedCardNumber");
            cardNumberDDL = dropDownList.options[dropDownList.selectedIndex].text;
            if (cardNumberDDL == "" && newCardNumber != "") {
                cardNumber = newCardNumber;
            }
            else {
                cardNumber = cardNumberDDL;
            }

            random = Math.floor((Math.random() * 10) + 1);

            if (random === 1 || usedCards.includes(cardNumber)) {
                if (!usedCards.includes(cardNumber)) {
                    usedCards.push(cardNumber);
                }
                alert("Lo sentimos, al parecer la tarjeta seleccionada no cuenta con fondos suficientes. Por favor seleccione otra.");
            }
            else {
                submitForm();
            }
        }
    }

    function submitForm() {
        document.getElementById('pform').submit();
    }
</script>