Models/Auction.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;

namespace TrendyShop.Models
{
    public class Auction
    {   
        [Display(Name ="Título")]
        public string Title { get; set; }
        
        public bool IsNew { get; set; }

        public string UserId { get; set; }

        [ForeignKey("UserId"), Column(Order = 0)]
        public User User { get; set; }

        public int ArticleId { get; set; }

        [Key, ForeignKey("ArticleId"), Column(Order = 1)]
        public Article Article { get; set; }

        public double CurrentPrice { get; set; }

        [Display(Name = "Duración")]
        public TimeSpan Duration { get; set; }

        [Display(Name = "Fecha de inicio")]
        public DateTime Start { get; set; }

        public bool IsFinished { get; set; }

        public bool HasStarted { get; set; }

        [ForeignKey("BidId"), Column(Order = 2)]
        public int BidId { get; set; }

        public Bid LastBid { get; set; }

        public int Biders{ get; set; }

        public double Min_Bid { get; set; }

        public bool Paid { get; set; }
    }
}

ViewModels/AuctionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrendyShop.Models;
using System.Diagnostics;

namespace TrendyShop.ViewModels
{
    public class AuctionViewModel
    {
        public int Id { get; set; }

        public Article Article { get; set; }

        public int ArticleId { get; set; }

        public string Name { get; set; }

        public string UserName { get; set; }

        public User User { get; set; }

        public string AuctionDescription { get; set; }

        public TimeSpan Duration { get; set; }

        public DateTime Start { get; set; }

        public bool IsFinished { get; set; }

        public bool HasStarted { get; set; }

        public int Biders { get; set; }

        public double Price { get; set; }

        public double BidAmount { get; set; }

        public Bid LastBid { get; set; }

        public double Min_Bid { get; set; }

        public bool Paid { get; set; }

        public string Winner { get; set; }
        
        public string Deadline { get; set; }
    }
}

ViewModels/NewAuctionViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using TrendyShop.Models;

namespace TrendyShop.ViewModels
{
    public class NewAuctionViewModel
    {
        public int Id { get; set; }

        public IEnumerable<Category> Categories { get; set; }

        public Auction Auction { get; set; }

        [Display(Name ="Imagen")]
        public IFormFile Image { get; set; }
    }
}

Controllers/AuctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TrendyShop.Data;
using TrendyShop.ViewModels;
using TrendyShop.Models;
using Microsoft.EntityFrameworkCore;
using System.Web;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace TrendyShop.Controllers
{
    public class AuctionController : Controller
    {
        private EFDbContext context;
        private IWebHostEnvironment webHostEnvironment;

        public AuctionController(EFDbContext ctx, IWebHostEnvironment hostEnvironment)
        {
            context = ctx;
            webHostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            var date = DateTime.Now;
            var vm = new AuctionIndexViewModel
            {
                Auctions = context.Auctions.Include(a => a.Article).ToList().Where(a=> a.Start <= date && a.Start + a.Duration > date || a.Start > date),
                Categories = context.Categories.ToList(),
                UserIsAdmin = User.IsInRole("Admin")
            };

            return View(vm);
        }

        public IActionResult MyAuctions()
        {
            var currentUserName = User.Identity.Name;
            var userId = context.Users.Single(u => u.UserName == currentUserName).Id;

            var date = DateTime.Now;
            var vm = new AuctionIndexViewModel
            {
                Auctions = context.Auctions.Include(a => a.Article).Where(a => a.UserId == userId).ToList(),
                Categories = context.Categories.ToList()
            };

            return View(vm);
        }

        public IActionResult AllFilter(bool myAucts = false)
        {
            var vm = new AuctionIndexViewModel
            {
                Categories = context.Categories.ToList()
            };

            if (myAucts)
            {
                var userName = User.Identity.Name;
                var userId = context.Users.Single(u => u.UserName == userName).Id;
                vm.Auctions = context.Auctions.Include(a => a.Article).Where(a => a.UserId == userId).ToList();
                return View("MyAuctions",vm);
            }

            vm.Auctions = context.Auctions.Include(a => a.Article).ToList();
            return View("Index", vm);
        }
        
        public IActionResult CategoryFilter(int categoryId, bool myAucts = false)
        {
            var vm = new AuctionIndexViewModel
            {
                Categories = context.Categories.ToList()
            };

            if (myAucts)
            {
                var userName = User.Identity.Name;
                var userId = context.Users.Single(u => u.UserName == userName).Id;
                vm.Auctions = context.Auctions.Include(a => a.Article)
                                              .Include(a => a.User)
                                              .Where(a => a.Article.CategoryId == categoryId && a.UserId == userId)
                                              .ToList();
                return View("MyAuctions", vm);
            }

            vm.Auctions = context.Auctions.Include(a => a.Article)
                                          .Include(a => a.User)
                                          .Where(a => a.Article.CategoryId == categoryId)
                                          .ToList();
            return View("Index", vm);
        }

        public IActionResult ConditionFilter(bool isNew, bool myAucts = false)
        {
            var vm = new AuctionIndexViewModel
            {
                Categories = context.Categories.ToList()
            };

            IQueryable<Auction> auctions;
            if (isNew)
            {
                auctions = context.Auctions.Include(a => a.Article).Include(a => a.User).Where(a => a.Article.IsNew);
            }
            else
            {
                auctions = context.Auctions.Include(a => a.Article).Include(a => a.User).Where(a => !a.Article.IsNew);
            }

            if (myAucts)
            {
                var userName = User.Identity.Name;
                if (userName != null)
                {
                    var userId = context.Users.Single(u => u.UserName == userName).Id;
                    vm.Auctions = auctions.Where(a => a.UserId == userId).ToList();
                    return View("MyAuctions", vm);
                }//else mandar error aqui y en todos los filtros
            }

            vm.Auctions = auctions.ToList();
            return View("Index", vm);
        }

        public IActionResult PriceFilter(float minp, float maxp, bool myAucts = false)
        {
            var vm = new AuctionIndexViewModel
            {
                Categories = context.Categories.ToList()
            };

            if (myAucts)
            {
                var userName = User.Identity.Name;
                var userId = context.Users.Single(u => u.UserName == userName).Id;
                vm.Auctions = context.Auctions.Include(a => a.Article).Include(a => a.User).Where(a => (a.Article.Price >= minp && a.Article.Price <= maxp) && a.UserId == userId).ToList();
                return View("MyAuctions", vm);
            }

            vm.Auctions = context.Auctions.Include(a => a.Article).Include(a => a.User).Where(a => (a.Article.Price >= minp && a.Article.Price <= maxp)).ToList();

            return View("Index", vm);
        }

        public IActionResult StateFilter(int state, bool myAucts = false)
        {
            var vm = new AuctionIndexViewModel
            {
                Categories = context.Categories.ToList()
            };

            var date = DateTime.Now;
            if (state == 1)//pasadas
            {
                vm.Auctions = context.Auctions.Include(a => a.Article).Include(a => a.User).ToList().Where(a => a.Duration < date - a.Start);
            }
            else if (state == 2)//en curso
            {
                vm.Auctions = context.Auctions.Include(a => a.Article).Include(a => a.User).ToList().Where(a => a.Start <= date && a.Start + a.Duration > date);

                //auctions = context.Auctions.Include(a => a.Article).Include(a => a.User).Where(a => a.Start <= date && a.Start + a.Duration > date);
            }
            else//pendientes
            {
                vm.Auctions = context.Auctions.Include(a => a.Article).Include(a => a.User).Where(a => a.Start > date).ToList();
            }

            if (myAucts)
            {
                var userName = User.Identity.Name;
                if (userName != null)
                {
                    var userId = context.Users.Single(u => u.UserName == userName).Id;
                    vm.Auctions = vm.Auctions.Where(a => a.UserId == userId);
                    return View("MyAuctions", vm);
                }//else mandar error aqui y en todos los filtros
            }

            return View("Index", vm);
        }

        public IActionResult Search(string search, bool myAucts = false)
        {
            var vm = new AuctionIndexViewModel
            {
                Categories = context.Categories.ToList()
            };

            if (myAucts)
            {
                var userName = User.Identity.Name;
                var userId = context.Users.Single(u => u.UserName == userName).Id;
                vm.Auctions = context.Auctions.Include(a => a.Article).Include(a => a.User).Where(a => a.Article.Name.Contains(search) && a.UserId == userId).ToList();
                return View("MyAuctions", vm);
            }

            vm.Auctions = context.Auctions.Include(a => a.Article).Include(a => a.User).Where(a => a.Article.Name.Contains(search)).ToList();
            return View("Index", vm);
        }

        public IActionResult Details(int id)
        {
            var auction = context.Auctions.Find(id);

            context.Entry(auction).Reference(a => a.User).Load();
            context.Entry(auction).Reference(a => a.Article).Load();
            context.Entry(auction).Reference(a => a.LastBid).Load();

            var winner = context.Users.Find(auction.LastBid.UserId);

            
            string deadline = (auction.Start + auction.Duration).ToString("yyyy-MM-dd hh:mm");
            var result = new AuctionViewModel
            {
                UserName = auction.User.UserName,
                User = GetUser(auction.User.UserName),
                Duration = auction.Duration,
                Start = auction.Start,
                Article = auction.Article,
                ArticleId = auction.ArticleId,
                Name = auction.Title,
                AuctionDescription = auction.Article.Description,
                Price = auction.CurrentPrice,
                LastBid = auction.LastBid,
                IsFinished = auction.IsFinished,
                HasStarted = auction.HasStarted,
                Biders = auction.Biders,
                Min_Bid = auction.Min_Bid,
                Paid = auction.Paid,
                Winner = winner.UserName,
                Deadline = deadline
            };

            //Checks if the auction has started
            if (auction.Start <= DateTime.Now)
            {
                auction.HasStarted = true;
                result.HasStarted = true;
                context.SaveChanges();
            }
            //Checks if the auction is over
            if (auction.Duration < DateTime.Now - auction.Start)
            {
                auction.IsFinished = true;
                result.IsFinished = true;
                context.SaveChanges();
            }
            return View(result);
        }

        public IActionResult Bid(AuctionViewModel viewModel)
        {
            var auction = context.Auctions.Find(viewModel.ArticleId);
            var creator = context.Users.Find(auction.UserId);

Views/Auction/Details.cshtml
@using TrendyShop.ViewModels
@model AuctionViewModel
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<User> SignInManager

<!DOCTYPE html>
<html lang="en">

<body>
    <!-- Page Content -->
    @{
        TimeSpan elapsed = DateTime.Now - Model.Start;
        TimeSpan remaining = Model.Duration - elapsed;
        if (elapsed > Model.Duration) remaining = new TimeSpan(0);
        string winner = "-";
        if (Model.Biders > 0)
        {
            winner = Model.LastBid.user.UserName;
        }
    }
    <div class="col-lg-7 mx-auto mt-4">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title border-bottom">@Model.Name</h3>

                <div class="d-flex">
                    <img src="~/images/@Model.Article.Image" class="img-fluid rounded" height="200" width="300" />
                    <div class=" ml-2 flex-column">

                        <h3>@Model.Article.Name</h3>
                        <p class="card-text">@Model.Article.Description</p>
                    </div>
                </div>
                <div class="d-flex mt-4">
                    @if (Model.IsFinished)
                    {
                        <p title="Fecha"><i class="far fa-calendar-check"></i> @Model.Start.ToString("dd/MM/yy")</p>
                    }
                    else
                    {
                        <p title="Fecha"><i class="far fa-calendar-alt"></i> @Model.Start.ToString("dd/MM/yy")</p>
                    }
                    <p title="Hora de inicio" class="ml-2"><i class="far fa-clock"></i> @Model.Start.ToString("hh:mm tt")</p>
                    <p title="Tiempo restante (días/horas/min/seg)" class="ml-2">
                        <i class="fas fa-hourglass-end"></i>
                        <div id="clockdiv">
                            <span class="days"></span>:
                            <span class="hours"></span>:
                            <span class="minutes"></span>:
                            <span class="seconds"></span>
                        </div>
                    </p>
                    <h5 title="Participantes" class="ml-2"><i class="fas fa-users"></i> @Model.Biders</h5>

                </div>
                @if (Model.IsFinished)
                {
                    <h5>Vendido a: @winner </h5>

                }
                else if (Model.HasStarted && !Model.IsFinished) /*---------Si está en curso---------*/
                {
                    <h5 class="mb-0">Licitador en cabeza: @winner </h5>
                }
                <div class="d-flex">
                    <h5 class="btn btn-secondary mt-0">Precio Inicial: @Model.Article.Price$</h5>
                    @if (Model.IsFinished) // si ya se terminó
                    {
                        <h5 class="ml-2 btn btn-secondary">Precio Final: @Model.Price$</h5>
                    }
                    else if (Model.HasStarted && !Model.IsFinished) /*---------Si está en curso---------*/
                    {
                        <h5 class="ml-2 btn btn-secondary mt-0">Precio Actual: @Model.LastBid.amount$</h5>
                    }

                </div>
                @if (SignInManager.IsSignedIn(User) && !Model.IsFinished && Model.HasStarted) //Only a logged user can participate
                {
                    <form asp-controller="Auction" asp-action="Bid" method="post">
                        <h5 class="text-lg-left">Cantidad:</h5>
                        <div class="d-flex">
                            <input type="text" asp-for="BidAmount" class=" form-control" id="submit" required data-validation-required-message="Por favor introduzca una cantidad.">
                            <span asp-validation-for="BidAmount" class="text-danger"></span>
                            <input type="text" asp-for="ArticleId" data="@Model.Id" id="submit" hidden /> @*NO BORRAR*@
                            <button type="submit" class="ml-2 bg-dark btn btn-dark">Pujar</button>
                            <div asp-validation-summary="All" class="col-lg-4 text-danger"></div>
                        </div>
                    </form>

                }
                @if (SignInManager.IsSignedIn(User) && Model.IsFinished && !Model.Paid) //For the winner only
                {
                    <form asp-controller="Buy" asp-action="BuyAuctionArticle" asp-route-aid="@Model.ArticleId"method="post">
                        <div class="mb-4">
                            @*<input type="text" asp-for="aid" data="@Model.ArticleId" id="submit" hidden />*@
                            <button type="submit" class="bg-dark btn btn-dark">Finalizar Subasta</button>
                        </div>
                    </form>
                }
            </div>

        </div>
    </div>
</body>
</html>
<script>
    function getTimeRemaining(endtime) {
        const total = Date.parse(endtime) - Date.parse(new Date());
        const seconds = Math.floor((total / 1000) % 60);
        const minutes = Math.floor((total / 1000 / 60) % 60);
        const hours = Math.floor((total / (1000 * 60 * 60)) % 24);
        const days = Math.floor(total / (1000 * 60 * 60 * 24));

        return {
            total,
            days,
            hours,
            minutes,
            seconds
        };
    }

    function initializeClock(id, endtime) {
        const clock = document.getElementById(id);
        const daysSpan = clock.querySelector('.days');
        const hoursSpan = clock.querySelector('.hours');
        const minutesSpan = clock.querySelector('.minutes');
        const secondsSpan = clock.querySelector('.seconds');

        function updateClock() {
            const t = getTimeRemaining(endtime);
            if (t.total <= 0) {
                clearInterval(timeinterval);
            }
            daysSpan.innerHTML = t.days;
            hoursSpan.innerHTML = ('0' + t.hours).slice(-2);
            minutesSpan.innerHTML = ('0' + t.minutes).slice(-2);
            secondsSpan.innerHTML = ('0' + t.seconds).slice(-2);

            
        }

        updateClock();
        const timeinterval = setInterval(updateClock, 1000);
    }

    const deadline = new Date( "@Model.Deadline");
    initializeClock('clockdiv', deadline);
</script>

Views/Auction/Index.cshtml
@using TrendyShop.ViewModels
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model AuctionIndexViewModel

<!DOCTYPE html>
<html lang="en">

<body>

    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <h1 class="col-lg-4 mt-4 mb-3">Subastas</h1>

        <form asp-action="Search" asp-controller="Auction">
            <div class="d-flex">
                <div class="ml-auto">
                    <div class="d-flex">
                        <input type="search" class="form-control" id="search" name="search">
                        <button type="submit" class="btn btn-dark ml-1">Buscar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="/Home/Index">Inicio</a>
        </li>
        <li class="breadcrumb-item active">Subastas</li>
    </ol>

    <!-- Content Row -->
    <div class="row">
        <!-- Sidebar Column -->
        <div class="col-lg-3 mb-4">
            <div class="card">
                <div class="card-body">
                    <ul class="navbar-nav flex-column">
                        <li class="card-title border-bottom h2">
                            Filtrar por...
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link" data-toggle="collapse" aria-expanded="false" data-target="#submenu-0" aria-controls="submenu-0"><i class="fas fa-dollar-sign"></i> Precio</a>
                            <div id="submenu-0" class="collapse submenu" style="">
                                <form asp-controller="Auction" asp-action="PriceFilter">
                                    <ul class="nav flex-column">
                                        <li class="nav-item mb-1 ml-4">
                                            <div class="list-group-item">
                                                <div class="d-flex flex-column">
                                                    <label for="minp">Min</label>
                                                    <input type="number" name="minp" id="minp" />

                                                    <label for="maxp">Max</label>
                                                    <input type="number" name="maxp" id="maxp" />
                                                </div>
                                                <div class="d-flex">
                                                    <button type="submit" class="btn btn-dark mt-3 ml-auto">Filtrar</button>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </form>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-1" aria-controls="submenu-1"><i class="fas fa-chart-bar"></i> Categoría <span class="badge badge-success"></span></a>
                            <div id="submenu-1" class="collapse submenu" style="">
                                <ul class="nav flex-column">
                                    @foreach (Category cat in Model.Categories)
                                    {
                                        <li class="nav-item mb-1 ml-4">
                                            @Html.ActionLink(cat.Name, "CategoryFilter", "Auction", new { categoryId = cat.CategoryId })
                                        </li>
                                    }
                                    @if (Model.UserIsAdmin)
                                    {
                                        <li class="nav-item mb-1 ml-4">
                                            <a href="#" data-toggle="modal" data-target="#CategoryModal"><i class="fas fa-plus"></i> Añadir Categoría</a>
                                        </li>
                                    }
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-1-1" aria-controls="submenu-1-1"><i class="fas fa-gift"></i> Condición</a>
                            <div id="submenu-1-1" class="collapse submenu" style="">
                                <ul class="nav flex-column">
                                    <li class="nav-item mb-1 ml-4">
                                        @Html.ActionLink("Nuevo", "ConditionFilter", "Auction", new { isNew = true })
                                    </li>
                                    <li class="nav-item mb-1 ml-4">
                                        @Html.ActionLink("De Uso", "ConditionFilter", "Auction", new { isNew = false })
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-1-2" aria-controls="submenu-1-2"><i class="fas fa-parachute-box"></i> Estado</a>
                            <div id="submenu-1-2" class="collapse submenu" style="">
                                <ul class="nav flex-column">
                                    <li class="nav-item mb-1 ml-4">
                                        @Html.ActionLink("Cerradas", "StateFilter", "Auction", new { state = 1})
                                    </li>
                                    <li class="nav-item mb-1 ml-4">
                                        @Html.ActionLink("En curso", "StateFilter", "Auction", new { state = 2})
                                    </li>
                                    <li class="nav-item mb-1 ml-4">
                                        @Html.ActionLink("Pendientes", "StateFilter", "Auction", new { state = 3})
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a href="/Auction/Active "></a>
                        </li>
                        <li class="nav-item">
                            <a href="/Auction/AllFilter"><i class="fas fa-globe"></i> Ver todos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-lg-9 mb-4">
            <h2>Subastas</h2>

            @foreach (Auction a in Model.Auctions)
            {
                <div class="card">
                    <div class="card-body">
                        <img src="~/images/@a.Article.Image" class="img-fluid rounded" height="200" width="300" />
                        <h4 class="card-title border-bottom">@a.Title</h4>
                        <div class="d-flex">
                            <p><i class="far fa-calendar-alt"></i> @a.Start.ToString("dd/MM/yy")</p>
                            <p class="ml-2"><i class="far fa-clock"></i> @a.Start.ToString("hh:mm tt")</p>
                            <p class="ml-2"><i class="fas fa-hourglass-end"></i> @a.Duration</p>
                        </div>
                        <p>Artículo: @a.Article.Name</p>

                        <p class="card-text">@a.Article.Description</p>
                        <div class="d-flex">
                            <div class="ml-auto">
                                @*<a class="btn btn-primary">Unirse </a>*@
                                @Html.ActionLink("Detalles", "Details", "Auction", new { id = a.ArticleId }, null)
                                @if (User.IsInRole("Admin"))
                                {
                                    @Html.ActionLink("Eliminar", "Delete", "Auction", new { aid = a.ArticleId, fromIndex = true }, null)
                                }
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
    <div class="modal fade" id="CategoryModal" tabindex="-1" role="dialog" aria-labelledby="CategoryModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <button type="button" class="close ml-auto" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <form asp-action="SaveAddCategory" asp-controller="User">
                        <div class="flex-column">
                            @Html.LabelFor(m => m.CategoryName)
                            <div class="d-flex">
                                @Html.TextBoxFor(m => m.CategoryName, new { @class = "form-group" })
                                @Html.ValidationMessageFor(m => m.CategoryName)
                                <button class="btn btn-secondary ml-2 form-group" type="submit">Añadir</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->
    <!-- Footer -->
    <!-- Bootstrap core JavaScript -->

</body>

</html>